version: "3.9"

services:
  backend:
    build: .
    container_name: edusystem_backend
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"

  nginx:
    image: nginx:1.27.4
    container_name: edusystem_nginx_proxy
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
